use futebol;

SELECT * FROM BRASILEIRAO2;
# SELECIONANDO 5 TIMES COM MAIOR NUMERO DE TITULOS

SELECT NOME, TI_NACIONAIS, TI_INTERNAC, (TI_NACIONAIS + TI_INTERNAC) TOTAL  FROM
(SELECT * FROM BRASILEIRAO1
UNION ALL
SELECT * FROM BRASILEIRAO2) AS TIMES ORDER BY TOTAL DESC LIMIT 5;



# TIMES QUE NÃO POSSUEM NENHUM TÍTULO NACIONAL/INTERNACIONAL

SELECT * FROM
(SELECT * FROM BRASILEIRAO1
UNION ALL
SELECT * FROM BRASILEIRAO2) AS TABELA WHERE TI_NACIONAIS = 0 AND TI_INTERNAC = 0;



# SELECIONANDO TODOS OS TIMES CENTENÁRIOS

SELECT * FROM
(SELECT * FROM BRASILEIRAO1
UNION ALL
SELECT * FROM BRASILEIRAO2) AS TIMES WHERE IDADE >= 100 ORDER BY IDADE DESC;



# SELECIONANDO TIMES COM MENOS DE 50 ANOS

SELECT * FROM
(SELECT * FROM BRASILEIRAO1
UNION ALL
SELECT * FROM BRASILEIRAO2) AS TIMES WHERE IDADE < 50;



# ESTADOS COM MAIS TIMES ENTRE SÉRIES A E B

SELECT ESTADO, COUNT(*) AS TOTAL FROM
(SELECT * FROM BRASILEIRAO1
UNION ALL
SELECT * FROM BRASILEIRAO2) AS TABELA GROUP BY ESTADO ORDER BY TOTAL DESC;