USE FUTEBOL;

# COM O FAVORITISMO DO PALMEIRAS AO TITULO DO CAMPEONATO BRASILEIRO,
# VAMOS ADICIONAR UM TITULO NACIONAL PARA O PALMEIRAS

UPDATE BRASILEIRAO1 SET TI_NACIONAIS = TI_NACIONAIS + 1 WHERE NOME = 'Palmeiras';


# DEVIDO A INTERDIÇÃO DO ESTÁDIO ILHA DO RETIRO POR CONTA DA INVASÃO DA TORCIDA DO SPORT, 
# O TIME DEVERÁ MANDAR SEUS JOGOS EM OUTRO ESTÁDIO

UPDATE BRASILEIRAO2 SET ESTADIO = 'Aflitos' WHERE NOME = 'Sport';